spring.application.name=ai-credential-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/credentialDB
spring.datasource.username=B0337465
spring.datasource.password=ePciaE@12

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

